DROP DATABASE IF EXISTS burger_DB;
CREATE DATABASE burger_DB;

USE burger_DB;

CREATE TABLE yourBurgers(
  ID INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(100) NOT NULL,
  devoured BOOLEAN() DEFAULT FALSE,
  PRIMARY KEY (id)
);

